# Generated by Django 5.2 on 2025-05-08 13:24

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('market', models.CharField(blank=True, max_length=50, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=50, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historical_data',
                'managed': False,
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='idx_symbol')],
                'constraints': [
                    models.UniqueConstraint(fields=['timestamp', 'symbol'], name='unique_timestamp_symbol')
                ],
            },
        ),
        migrations.CreateModel(
            name='TempHistoricalData',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('market', models.CharField(blank=True, max_length=50, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=50, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'temp_historical_data',
                'managed': False,
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='idx_symbol_temp')],
                'constraints': [
                    models.UniqueConstraint(fields=['timestamp', 'symbol'], name='unique_timestamp_symbol_temp')
                ],
            },
        ),
    ]