# Generated by Django 5.2 on 2025-05-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ejemplo: EUR/USD, XAU/USD, AAPL', max_length=10, unique=True)),
                ('symbol', models.CharField(help_text='Formato para historical_data, ej: EURUSD, XAUUSD, AAPL', max_length=10, unique=True)),
                ('entity_type', models.CharField(choices=[('currency_pair', 'Par de divisas'), ('commodity', 'Commodity'), ('equity', 'Acción'), ('interest_rate', 'Tasa de interés'), ('cryptocurrency', 'Criptomoneda')], help_text='Tipo de entidad', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Descripción opcional', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Indica si la entidad está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entidad Soportada',
                'verbose_name_plural': 'Entidades Soportadas',
            },
        ),
        migrations.CreateModel(
            name='SupportedMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('markets_affected', models.CharField(max_length=200)),
                ('symbols_affected', models.CharField(max_length=200)),
            ],
        ),
    ]
