# Generated by Django 5.2 on 2025-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('markets_affected', models.CharField(max_length=200)),
                ('symbols_affected', models.CharField(max_length=200)),
            ],
        ),
    ]
