-- Exportación de la tabla core_app_supportedminute
INSERT INTO core_app_supportedminute (id, name, description, impact, country, source, frequency, markets_affected, symbols_affected) VALUES
(614, 'Labor Day', 'Imported from MetaTrader 5', 'nan', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(615, 'Workers’ Day', 'Imported from MetaTrader 5', 'nan', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(616, 'Exports y/y', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(617, 'Imports y/y', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(618, 'Trade Balance', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(619, 'au Jibun Bank Manufacturing PMI', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(620, 'Exports m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(621, 'Imports m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(622, 'Export Price Index q/q', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(623, 'Import Price Index q/q', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(624, 'BoJ Monetary Policy Statement', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(625, 'BoJ Outlook Report', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(626, 'BoJ Interest Rate Decision', 'Imported from MetaTrader 5', 'High', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(627, 'Consumer Confidence Index', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(628, 'BoJ Press Conference', 'Imported from MetaTrader 5', 'High', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(629, 'RBA Index of Commodity Prices y/y', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(630, 'Retail Sales y/y', 'Imported from MetaTrader 5', 'Low', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(631, 'BoE Consumer Credit m/m', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(632, 'BoE M4 Money Supply m/m', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(633, 'BoE Mortgage Approvals', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(634, 'BoE Mortgage Lending m/m', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(635, 'BoE Net Lending to Individuals m/m', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(636, 'S&P Global/CIPS Manufacturing PMI', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(637, 'Challenger Job Cuts', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(638, 'Challenger Job Cuts y/y', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(639, 'Initial Jobless Claims', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(640, 'Continuing Jobless Claims', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(641, 'Initial Jobless Claims 4-Week Average', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(642, 'S&P Global Manufacturing PMI', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(643, 'ISM Manufacturing PMI', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(644, 'ISM Manufacturing Prices Paid', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(645, 'ISM Manufacturing Employment', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(646, 'ISM Manufacturing New Orders', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(647, 'Construction Spending m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(648, 'EIA Natural Gas Storage Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(649, '4-Week Bill Auction', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(650, '8-Week Bill Auction', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(651, 'Building Consents m/m', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(652, 'CPI m/m', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(653, 'CPI y/y', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(654, 'Unemployment Rate', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(655, 'Jobs to Applicants Ratio', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(656, 'BoJ Monetary Base y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(657, 'Foreign Bond Investment', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(658, 'Foreign Investment in Japan Stocks', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(659, 'Constitution Memorial Day', 'Imported from MetaTrader 5', 'nan', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(660, 'Retail Sales m/m', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(661, 'PPI q/q', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(662, 'PPI y/y', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(663, 'Retail Sales q/q', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(664, 'Silf/Swedbank Manufacturing PMI', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(665, 'Government Budget Balance', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(666, 'New Car Registrations m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(667, 'New Car Registrations y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(668, 'procure.ch Manufacturing PMI', 'Imported from MetaTrader 5', 'Medium', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(669, 'NAV Unemployment Rate n.s.a.', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(670, 'DNB/NIMA Manufacturing PMI', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(671, 'ECB Economic Bulletin', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(672, 'GDP q/q', 'Imported from MetaTrader 5', 'Low', 'HKD', 'MetaTrader 5', 'Unknown', 'Forex', 'HKD'),
(673, 'GDP y/y', 'Imported from MetaTrader 5', 'Low', 'HKD', 'MetaTrader 5', 'Unknown', 'Forex', 'HKD'),
(674, 'Trade Balance Non-EU', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(675, 'Absa Manufacturing PMI', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(676, 'Core CPI m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(677, 'Core CPI y/y', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(678, 'CPI excl. Energy and Unprocessed Food m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(679, 'CPI excl. Energy and Unprocessed Food y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(680, 'CPI', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(681, 'Core CPI', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(682, 'Bank Loan Growth y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(683, 'Deposit Growth y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(684, 'Foreign Exchange Reserves', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(685, 'Total New Vehicle Sales', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(686, 'Total New Vehicle Sales m/m', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(687, 'Total New Vehicle Sales y/y', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(688, 'Nonfarm Payrolls', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(689, 'Participation Rate', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(690, 'Average Hourly Earnings m/m', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(691, 'Average Hourly Earnings y/y', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(692, 'Average Weekly Hours', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(693, 'Government Payrolls', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(694, 'Private Nonfarm Payrolls', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(695, 'U6 Unemployment Rate', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(696, 'Manufacturing Payrolls', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(697, 'SIPMM PMI', 'Imported from MetaTrader 5', 'Low', 'SGD', 'MetaTrader 5', 'Unknown', 'Forex', 'SGD'),
(698, 'Factory Orders m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(699, 'Factory Orders excl. Transportation m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(700, 'Nondefense Capital Goods Shipments excl. Aircraft m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(701, 'Baker Hughes US Oil Rig Count', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(702, 'Baker Hughes US Total Rig Count', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(703, 'CFTC AUD Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(704, 'CFTC BRL Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(705, 'CFTC CAD Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(706, 'CFTC JPY Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(707, 'CFTC MXN Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(708, 'CFTC NZD Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(709, 'CFTC ZAR Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(710, 'CFTC CHF Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(711, 'CFTC GBP Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(712, 'CFTC Copper Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(713, 'CFTC Silver Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(714, 'CFTC Gold Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(715, 'CFTC Crude Oil Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(716, 'CFTC S&P 500 Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(717, 'CFTC Aluminium Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(718, 'CFTC Corn Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(719, 'CFTC Natural Gas Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(720, 'CFTC Soybeans Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(721, 'CFTC Wheat Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(722, 'CFTC Nasdaq 100 Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(723, 'CFTC EUR Non-Commercial Net Positions', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(724, 'Greenery Day', 'Imported from MetaTrader 5', 'nan', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(725, 'Fed Governor Cook Speech', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(726, 'Early May Bank Holiday', 'Imported from MetaTrader 5', 'nan', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(727, 'Children''s Day', 'Imported from MetaTrader 5', 'nan', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(728, 'Buddha''s Birthday', 'Imported from MetaTrader 5', 'nan', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(729, 'The Birthday of the Buddha', 'Imported from MetaTrader 5', 'nan', 'HKD', 'MetaTrader 5', 'Unknown', 'Forex', 'HKD'),
(730, 'Anniversary of the Battle of Puebla', 'Imported from MetaTrader 5', 'nan', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(731, 'S&P Global Services PMI', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(732, 'S&P Global Composite PMI', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(733, 'ANZ Job Advertisements m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(734, 'FIPE CPI m/m', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(735, 'Sentix Investor Confidence', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(736, 'BCB Focus Market Report', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(737, '3-Month BTF Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(738, '6-Month BTF Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(739, '12-Month BTF Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(740, 'ISM Non-Manufacturing PMI', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(741, 'ISM Non-Manufacturing Employment', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(742, 'ISM Non-Manufacturing New Orders', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(743, 'ISM Non-Manufacturing Prices Paid', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(744, 'ISM Non-Manufacturing Business Activity', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(745, 'CB Employment Trends Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(746, 'Bbk Executive Board Member Mauderer Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(747, '3-Month Bill Auction', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(748, '6-Month Bill Auction', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(749, '3-Year Note Auction', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(750, 'S&P Global PMI', 'Imported from MetaTrader 5', 'Low', 'SGD', 'MetaTrader 5', 'Unknown', 'Forex', 'SGD'),
(751, 'ANZ Commodity Price Index m/m', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(752, 'Building Approvals m/m', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(753, 'Private House Approvals m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(754, 'Caixin Services PMI', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(755, 'Caixin Composite PMI', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(756, 'Unemployment Rate n.s.a.', 'Imported from MetaTrader 5', 'Low', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(757, 'Industrial Production m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(758, 'Unemployment Change', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(759, 'S&P Global/CIPS Services PMI', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(760, 'S&P Global/CIPS Composite PMI', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(761, 'PPI m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(762, '6-Month Letras Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(763, '12-Month Letras Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(764, '5-Year Note Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(765, 'Gross Fixed Investments m/m', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(766, 'Gross Fixed Investments n.s.a. y/y', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(767, 'Exports', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(768, 'Imports', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(769, 'Ivey PMI', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(770, 'Ivey PMI n.s.a.', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(771, 'GDT Price Index', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(772, 'EIA Short-Term Energy Outlook', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(773, '10-Year Note Auction', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(774, 'RBNZ Financial Stability Report', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(775, 'Employment Change q/q', 'Imported from MetaTrader 5', 'High', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(776, 'Labor Cost Index q/q', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(777, 'Labor Cost Index y/y', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(778, 'RBNZ Governor Orr Speech', 'Imported from MetaTrader 5', 'High', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(779, 'Ai Group Industry Index', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(780, 'Ai Group Manufacturing Index', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(781, 'Ai Group Construction Index', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(782, 'Victory Day', 'Imported from MetaTrader 5', 'nan', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(783, 'au Jibun Bank Services PMI', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(784, 'au Jibun Bank Composite PMI', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(785, 'Factory Orders y/y', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(786, 'Nonfarm Payrolls q/q', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(787, 'Foreign Currency Reserves', 'Imported from MetaTrader 5', 'Low', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(788, 'S&P Global Construction PMI', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(789, 'S&P Global/CIPS Construction PMI', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(790, '10-Year OAT Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(791, '5-Year Treasury Gilt Auction', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(792, 'Industrial Production y/y', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(793, 'EIA Crude Oil Stocks Change', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(794, 'EIA Cushing Crude Oil Stocks Change', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(795, 'EIA Crude Oil Imports Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(796, 'EIA Distillate Fuel Production Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(797, 'EIA Distillates Stocks Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(798, 'EIA Gasoline Production Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(799, 'EIA Heating Oil Stocks Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(800, 'EIA Gasoline Stocks Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(801, 'EIA Refinery Crude Oil Daily Inputs Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(802, 'EIA Refinery Utilization Rate Change', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(803, 'Foreign Exchange Flows', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(804, 'FOMC Statement', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(805, 'Fed Interest Rate Decision', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(806, 'FOMC Press Conference', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(807, 'Fed Consumer Credit m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(808, 'BCB Interest Rate Decision', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(809, 'RICS House Price Balance', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(810, 'BoJ Monetary Policy Meeting Minutes', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(811, '10-Year JGB Auction', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(812, 'Halifax HPI m/m', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(813, 'Halifax HPI y/y', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(814, 'Manufacturing Production m/m', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(815, 'Manufacturing Production y/y', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(816, 'Gross International Reserves', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(817, 'Net International Reserves', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(818, 'Trade Balance n.s.a.', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(819, 'Norges Bank Interest Rate Decision', 'Imported from MetaTrader 5', 'Medium', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(820, 'Bbk Executive Board Member Balz Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(821, '3-Year Bonos Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(822, '5-Year Bonos Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(823, '30-Year Obligacion Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(824, 'BoE MPC Meeting Minutes', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(825, 'BoE Interest Rate Decision', 'Imported from MetaTrader 5', 'High', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(826, 'BoE MPC Vote Cut', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(827, 'BoE MPC Vote Hike', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(828, 'BoE MPC Vote Unchanged', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(829, 'FGV IGP-DI Inflation Index m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(830, 'BoE Monetary Policy Report', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(831, 'Nonfarm Productivity q/q', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(832, 'Unit Labor Costs q/q', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(833, 'ECB Supervisory Board Member Tuominen Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(834, 'BoE Governor Bailey Speech', 'Imported from MetaTrader 5', 'High', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(835, 'ANFAVEA Auto Production m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(836, 'ANFAVEA Auto Sales m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(837, 'Wholesale Inventories m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(838, 'Wholesale Sales m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(839, '30-Year Bond Auction', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(840, 'Current Account', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(841, 'Labor Cash Earnings y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(842, 'Overtime Pay y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(843, 'Real Wage y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(844, 'Household Spending y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(845, 'Household Spending m/m', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(846, 'International Reserves', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(847, 'Coincident Index', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(848, 'Leading Index', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(849, 'Coincident Index m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(850, 'Leading Index m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(851, 'Industrial New Orders m/m', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(852, 'Industrial New Orders y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(853, 'Household Consumption m/m', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(854, 'Household Consumption y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(855, 'Private Sector Production m/m', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(856, 'Private Sector Production y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(857, 'Consumer Climate', 'Imported from MetaTrader 5', 'Low', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(858, '12-Month BOT Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(859, 'Fed Vice Chair for Supervision Barr Speech', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(860, 'BoE MPC Member Pill Speech', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(861, 'Consumer Confidence Indicator', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(862, 'Consumer Confidence Indicator n.s.a.', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(863, 'CPI s.a. m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(864, 'Employment Change', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(865, 'Full-Time Employment Change', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(866, 'Part-Time Employment Change', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(867, 'FOMC Member Williams Speech', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(868, 'ECB Executive Board Member Schnabel Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(869, 'Fed Governor Waller Speech', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(870, 'Vesak Day', 'Imported from MetaTrader 5', 'nan', 'SGD', 'MetaTrader 5', 'Unknown', 'Forex', 'SGD'),
(871, 'Buddha Purnima', 'Imported from MetaTrader 5', 'nan', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(872, 'BoJ Bank Lending y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(873, 'Current Account n.s.a.', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(874, 'Goods Trade Balance', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(875, 'Adjusted Current Account', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(876, 'Eurogroup Meeting', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(877, 'Economy Watchers Index for Current Conditions', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(878, 'Economy Watchers Index for Future Conditions', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(879, 'Industrial Production n.s.a. y/y', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(880, 'BoE MPC Member Mann Speech', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(881, 'WASDE Report', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(882, 'Fed Senior Loan Officer Opinion Survey on Bank Lending Practices', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(883, 'Federal Budget Balance', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(884, 'BoJ M2 Money Stock y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(885, 'BoJ M3 Money Stock y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(886, 'BoJ L Money Stock y/y', 'Imported from MetaTrader 5', 'High', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(887, 'BoJ Summary of Opinions', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(888, 'Westpac-MI Consumer Sentiment m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(889, '30-Year JGB Auction', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(890, 'Consumer Confidence', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(891, 'ZEW Economic Sentiment Indicator', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(892, 'ZEW Economic Situation', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(893, '3-Month Letras Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(894, '9-Month Letras Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(895, 'Unemployment', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(896, '2-Year Note Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(897, '3-Year BTP Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(898, '7-Year BTP Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(899, 'CPI n.s.a.', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(900, 'Real Earnings m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(901, 'CPI n.s.a. m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(902, 'Core CPI n.s.a. m/m', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(903, 'Core CPI n.s.a.', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(904, 'Cleveland Fed Median CPI m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(905, '52-Week Bill Auction', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(906, 'NFIB Small Business Optimism', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(907, 'Electronic Card Retail Sales m/m', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(908, 'Electronic Card Retail Sales y/y', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(909, 'Visitor Arrivals m/m', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(910, 'Net Permanent & Long-Term Migration', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(911, 'Visitor Arrivals y/y', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(912, 'BoJ Corporate Goods Price Index m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(913, 'BoJ Corporate Goods Price Index y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(914, 'Home Loans m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(915, 'Investment Housing Loans m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(916, 'Wage Price Index q/q', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(917, 'Wage Price Index y/y', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(918, 'Registered Unemployment Rate', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(919, 'CPIF m/m', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(920, 'CPIF y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(921, 'HICP m/m', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(922, 'HICP y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(923, 'WPI y/y', 'Imported from MetaTrader 5', 'Medium', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(924, 'WPI Manufactured Products y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(925, 'WPI Food y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(926, 'WPI Fuel & Energy y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(927, 'Riksbank Monetary Policy Meeting Minutes', 'Imported from MetaTrader 5', 'Medium', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(928, 'Bbk President Nagel Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(929, '10-Year Treasury Gilt Auction', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(930, 'OPEC Monthly Oil Market Report', 'Imported from MetaTrader 5', 'Medium', 'ALL', 'MetaTrader 5', 'Unknown', 'Forex', 'ALL'),
(931, 'Services Volume m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(932, 'Services Volume y/y', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(933, 'Building Permits m/m', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(934, 'Fed Governor Jefferson Speech', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(935, 'Food Price Index m/m', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(936, 'MI Inflation Expectations', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(937, 'PBC New Loans', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(938, 'PBC M2 Money Stock y/y', 'Imported from MetaTrader 5', 'Low', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(939, 'PBC Outstanding Loan Growth y/y', 'Imported from MetaTrader 5', 'Low', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(940, 'BOK M2 Money Supply y/y', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(941, 'GDP Mainland q/q', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(942, 'Machine Tool Orders y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(943, 'Wholesale Price Index m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(944, 'Wholesale Price Index y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(945, 'ECB Executive Board Member Elderson Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(946, 'IEA Monthly Oil Market Report', 'Imported from MetaTrader 5', 'Medium', 'ALL', 'MetaTrader 5', 'Unknown', 'Forex', 'ALL'),
(947, '3-Year OAT Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(948, '5-Year OAT Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(949, 'Employment Change y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(950, 'Employment Level', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(951, 'Mining Production m/m', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(952, 'Mining Production y/y', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(953, 'Gold Production y/y', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(954, 'Official Reserve Assets', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(955, 'ECB Vice President de Guindos Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(956, 'NIESR GDP Estimate', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(957, 'CMHC Housing Starts', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(958, 'Core Retail Sales m/m', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(959, 'Retail Control m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(960, 'Retail Sales excl. Autos and Gas m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(961, 'Philadelphia Fed Manufacturing Index', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(962, 'Philadelphia Fed Employment', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(963, 'Philadelphia Fed Business Conditions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(964, 'Philadelphia Fed Prices Paid', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(965, 'Philadelphia Fed New Orders', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(966, 'Philadelphia Fed Capex Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(967, 'Core PPI m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(968, 'Core PPI y/y', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(969, 'Manufacturing Sales m/m', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(970, 'Wholesale Trade m/m', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(971, 'NY Fed Empire State Manufacturing Index', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(972, 'RBI M3 Money Supply y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(973, 'Fed Chair Powell Speech', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(974, 'Fed Industrial Production m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(975, 'Fed Capacity Utilization Rate', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(976, 'Fed Manufacturing Production m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(977, 'Fed Industrial Production y/y', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(978, 'Business Inventories m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(979, 'Retail Inventories m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(980, 'Retail Inventories excl. Autos m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(981, 'NAHB Housing Market Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(982, 'BoE MPC Member Dhingra Speech', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1106, 'Business Confidence', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(983, 'Bank of Mexico Interest Rate Decision', 'Imported from MetaTrader 5', 'Medium', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(984, 'Export Price Index y/y', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(985, 'Import Price Index y/y', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(986, 'BusinessNZ Manufacturing Index', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(987, 'GDP Price Index y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(988, 'Private Non-Residential Investment q/q', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(989, 'Private Consumption q/q', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(990, 'Net Exports Contribution to GDP q/q', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(991, 'Constitution Day', 'Imported from MetaTrader 5', 'nan', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(992, 'Non-Oil Domestic Exports m/m', 'Imported from MetaTrader 5', 'Low', 'SGD', 'MetaTrader 5', 'Unknown', 'Forex', 'SGD'),
(993, 'Non-Oil Domestic Exports y/y', 'Imported from MetaTrader 5', 'Low', 'SGD', 'MetaTrader 5', 'Unknown', 'Forex', 'SGD'),
(994, 'RBNZ 2-Year Inflation Expectations', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(995, 'RBNZ Non-Resident Debt Holdings', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(996, 'BoJ Board Member Nakamura Speech', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(997, 'Capacity Utilization Rate', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(998, 'CPI FOI excl. Tobacco m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(999, 'CPI FOI excl. Tobacco y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1000, 'Trade Balance EU', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1001, 'Housing Starts', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1002, 'Building Permits', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1003, 'Housing Starts m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1004, 'Import Price Index m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1005, 'Export Price Index m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1006, 'Import Price Index excl. Petroleum m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1007, 'Foreign Securities Purchases', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1008, 'Foreign Securities Purchases by Canadians', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1009, 'Michigan Consumer Sentiment', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1010, 'Michigan Consumer Expectations', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1011, 'Michigan Current Conditions', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1012, 'Michigan Inflation Expectations', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1013, 'Michigan 5-Year Inflation Expectations', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1014, 'ECB Executive Board Member Lane Speech', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1015, 'TIC Net Long-Term Transactions', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1016, 'TIC Net Long-Term Transactions incl. Swaps', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1017, 'TIC Overall Net Capital Flow', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1018, 'TIC Net Foreign Purchases of Domestic Treasury Bonds & Notes', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1019, 'Victoria Day', 'Imported from MetaTrader 5', 'nan', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1020, 'BusinessNZ Services Index', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1021, 'PPI Input q/q', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1022, 'PPI Output q/q', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1023, 'Fixed Asset Investment y/y', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1024, 'Industrial Production YTD y/y', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1025, 'Retail Sales YTD y/y', 'Imported from MetaTrader 5', 'Low', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1026, 'Tertiary Industry Activity Index m/m', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1027, 'CPI excl. Tobacco m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1028, 'CPI excl. Tobacco y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1029, 'BCB IBC-Br Economic Activity', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1030, 'CB Leading Economic Index m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1031, 'Foreign Direct Investment YTD y/y', 'Imported from MetaTrader 5', 'Low', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1032, 'RBA Monetary Policy Statement', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1033, 'RBA Rate Statement', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1034, 'RBA Interest Rate Decision', 'Imported from MetaTrader 5', 'High', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1035, 'Unemployment Rate 3-Months', 'Imported from MetaTrader 5', 'Low', 'HKD', 'MetaTrader 5', 'Unknown', 'Forex', 'HKD'),
(1036, 'Construction Output m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1037, 'Construction Output y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1038, 'Common CPI y/y', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1039, 'Median CPI y/y', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1040, 'Trimmed CPI y/y', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1041, 'Trade Balance 12-Months', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1042, 'Adjusted Trade Balance', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1043, 'BCB National Monetary Council Meeting', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1044, 'RBA Chart Pack', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1045, 'RBNZ Credit Card Spending y/y', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1046, 'Capacity Utilization q/q', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1047, 'Core RPI m/m', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1048, 'Core RPI y/y', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1049, 'RPI m/m', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1050, 'RPI y/y', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1051, 'CPIH y/y', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1052, 'CPIH m/m', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1053, 'CPIH', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1054, 'ECB Financial Stability Review', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1055, 'HPI y/y', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1056, '10-Year Bond Auction', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1057, 'Retail Sales n.s.a. y/y', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1058, 'New Housing Price Index m/m', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1059, '20-Year Bond Auction', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1060, 'Core Machinery Orders m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1061, 'Core Machinery Orders y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1062, 'BoJ Board Member Noguchi Speech', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1063, 'OBEGAL Forecast', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1064, 'Budget Release', 'Imported from MetaTrader 5', 'High', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1065, 'Business Climate', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1066, 'Ifo Business Expectations', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1067, 'Ifo Current Business Situation', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1068, 'Ifo Business Climate', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1069, 'Bbk Monthly Report', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1070, 'Building Permits y/y', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(1071, 'ECB Monetary Policy Meeting Accounts', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1072, 'Economic Activity m/m', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1073, 'Economic Activity n.s.a. y/y', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1074, 'First Half-Month CPI m/m', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1075, 'First Half-Month Core CPI m/m', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1076, 'IPPI m/m', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1077, 'IPPI y/y', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1078, 'RMPI m/m', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1079, 'RMPI y/y', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1080, 'Chicago Fed National Activity Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1081, 'Existing Home Sales', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1082, 'Existing Home Sales m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1083, 'Kansas City Fed Manufacturing Composite Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1084, 'Kansas City Fed Manufacturing Production', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1085, '10-Year TIPS Auction', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1086, 'BoC Deputy Governor Gravelle Speech', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1087, 'Core Retail Sales q/q', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1088, 'GfK Consumer Confidence', 'Imported from MetaTrader 5', 'Low', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1089, 'CPI excl. Food and Energy y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1090, 'Business Inventories Change', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1091, 'Corporate Profits q/q', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1092, 'New Home Sales', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1093, 'New Home Sales m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1094, 'Current Account - GDP Ratio', 'Imported from MetaTrader 5', 'Low', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1095, 'Spring Bank Holiday', 'Imported from MetaTrader 5', 'nan', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1096, 'Memorial Day', 'Imported from MetaTrader 5', 'nan', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1097, 'General Public Domestic Loan Debt y/y', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(1098, 'FGV Consumer Confidence', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1099, 'Foreign Direct Investment', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1100, 'Jobseekers Total', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1101, 'BoJ Corporate Services Price Index y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1102, 'Industrial Profit YTD y/y', 'Imported from MetaTrader 5', 'Low', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1103, 'BoJ Trimmed Mean Core CPI y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1104, 'BoJ Weighted Median Core CPI y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1105, 'GfK Consumer Climate', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1107, 'Manufacturing Confidence', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1108, 'Inflation Expectations', 'Imported from MetaTrader 5', 'Medium', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1109, 'Economic Tendency Indicator', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1110, 'Business Climate Indicator', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1111, 'Industrial Confidence Indicator', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1112, 'Services Sentiment Indicator', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1113, 'Economic Sentiment Indicator', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1114, 'Consumer Price Expectations', 'Imported from MetaTrader 5', 'High', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1115, 'Industry Selling Price Expectations', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1116, '2-Year CTZ Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1117, 'Mid-Month CPI m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1118, 'Mid-Month CPI y/y', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1119, 'Durable Goods Orders m/m', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1120, 'Core Durable Goods Orders m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1121, 'Durable Goods Orders excl. Defense m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1122, 'Nondefense Capital Goods Orders excl. Aircraft m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1123, 'HPI m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1124, 'HPI', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1125, 'S&P/CS HPI Composite-20 y/y', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1126, 'S&P/CS HPI Composite-20 n.s.a. m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1127, 'S&P/CS HPI Composite-20 s.a. m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1128, 'CB Consumer Confidence Index', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1129, 'Dallas Fed Manufacturing Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1130, 'BOK Manufacturing BSI', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(1131, 'Ascension Day', 'Imported from MetaTrader 5', 'nan', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1132, 'Construction Work Done q/q', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1133, 'RBNZ Rate Statement', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1134, 'RBNZ Monetary Policy Statement', 'Imported from MetaTrader 5', 'Medium', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1135, 'RBNZ Interest Rate Decision', 'Imported from MetaTrader 5', 'High', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1136, 'Households Loans y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1137, 'Non-Financial Corporations Loans y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1138, 'M3 Money Supply y/y', 'Imported from MetaTrader 5', 'Low', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1139, 'Nationwide HPI m/m', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1140, 'Nationwide HPI y/y', 'Imported from MetaTrader 5', 'Medium', 'GBP', 'MetaTrader 5', 'Unknown', 'Forex', 'GBP'),
(1141, 'Consumer Spending m/m', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1142, 'Riksbank Financial Stability Report', 'Imported from MetaTrader 5', 'Medium', 'SEK', 'MetaTrader 5', 'Unknown', 'Forex', 'SEK'),
(1143, 'Unemployment n.s.a.', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1144, 'Credit Suisse Economic Expectations', 'Imported from MetaTrader 5', 'Low', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(1145, '6-Month BOT Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1146, 'Industrial Production FYTD y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(1147, 'Manufacturing Production FYTD y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(1148, 'Richmond Fed Manufacturing Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1149, 'Richmond Fed Manufacturing Shipments', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1150, 'Richmond Fed Services Revenues', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1151, 'Dallas Fed Services Revenues', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1152, 'Dallas Fed Services Business Activity', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1153, 'RBNZ Press Conference', 'Imported from MetaTrader 5', 'High', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1154, 'FOMC Minutes', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1155, 'ANZ Business Confidence', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1156, 'ANZ Activity Outlook', 'Imported from MetaTrader 5', 'Low', 'NZD', 'MetaTrader 5', 'Unknown', 'Forex', 'NZD'),
(1157, 'BOK Interest Rate Decision', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(1158, 'BOK Monetary Policy Board Meeting', 'Imported from MetaTrader 5', 'Medium', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(1159, 'Private New Capital Expenditure q/q', 'Imported from MetaTrader 5', 'Medium', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1160, 'Building Capital Expenditure q/q', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1161, '5-Year BTP Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1162, '10-Year BTP Auction', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1163, 'Industrial Sales m/m', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1164, 'Industrial Sales  y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1165, 'FGV IGP-M Inflation Index m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1166, 'BCB Bank Lending m/m', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1167, 'Unemployment Rate 3-months', 'Imported from MetaTrader 5', 'Medium', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1168, 'GDP Price Index q/q', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1169, 'Core PCE Price Index q/q', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1170, 'PCE Price Index q/q', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1171, 'Real PCE q/q', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1172, 'GDP Sales q/q', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1173, 'Pending Home Sales m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1174, 'Pending Home Sales y/y', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1175, 'Pending Home Sales Index', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1176, 'Bank of Mexico Monetary Policy Meeting Minutes', 'Imported from MetaTrader 5', 'Medium', 'MXN', 'MetaTrader 5', 'Unknown', 'Forex', 'MXN'),
(1177, 'Bank Loans', 'Imported from MetaTrader 5', 'Low', 'SGD', 'MetaTrader 5', 'Unknown', 'Forex', 'SGD'),
(1178, '7-Year Note Auction', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1179, 'Index of Services m/m', 'Imported from MetaTrader 5', 'Low', 'KRW', 'MetaTrader 5', 'Unknown', 'Forex', 'KRW'),
(1180, 'Tokyo CPI y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1181, 'Tokyo CPI excl. Food and Energy y/y', 'Imported from MetaTrader 5', 'High', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1182, 'Tokyo Core CPI y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1183, 'Tokyo CPI s.a. m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1184, 'Large Retailer''s Sales y/y', 'Imported from MetaTrader 5', 'Medium', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1185, 'Industrial Production Forecast 1-month Ahead m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1186, 'Industrial Production Forecast 2-month Ahead m/m', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1187, 'Dragon Boat Festival', 'Imported from MetaTrader 5', 'nan', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1188, 'Tuen Ng Festival', 'Imported from MetaTrader 5', 'nan', 'HKD', 'MetaTrader 5', 'Unknown', 'Forex', 'HKD'),
(1189, 'RBA Housing Credit m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1190, 'RBA Private Sector Credit m/m', 'Imported from MetaTrader 5', 'Low', 'AUD', 'MetaTrader 5', 'Unknown', 'Forex', 'AUD'),
(1191, 'Construction Orders y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1192, 'Housing Starts y/y', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1193, 'Annualized Housing Starts', 'Imported from MetaTrader 5', 'Low', 'JPY', 'MetaTrader 5', 'Unknown', 'Forex', 'JPY'),
(1194, 'SARB Private Sector Credit y/y', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(1195, 'SARB M3 Money Supply y/y', 'Imported from MetaTrader 5', 'Low', 'ZAR', 'MetaTrader 5', 'Unknown', 'Forex', 'ZAR'),
(1196, 'KOF Economic Barometer', 'Imported from MetaTrader 5', 'Medium', 'CHF', 'MetaTrader 5', 'Unknown', 'Forex', 'CHF'),
(1197, 'ECB M3 Money Supply y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1198, 'ECB Households Loans y/y', 'Imported from MetaTrader 5', 'Medium', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1199, 'ECB Non-Financial Corporations Loans y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1200, 'ECB Private Sector Loans y/y', 'Imported from MetaTrader 5', 'Low', 'EUR', 'MetaTrader 5', 'Unknown', 'Forex', 'EUR'),
(1201, 'NAV Unemployment Change', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(1202, 'Norges Bank Foreign Exchange Daily Purchase', 'Imported from MetaTrader 5', 'Low', 'NOK', 'MetaTrader 5', 'Unknown', 'Forex', 'NOK'),
(1203, 'HKMA M3 Money Supply y/y', 'Imported from MetaTrader 5', 'Low', 'HKD', 'MetaTrader 5', 'Unknown', 'Forex', 'HKD'),
(1204, 'Fiscal Balance', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(1205, 'Nominal Budget Balance', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1206, 'Primary Budget balance', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1207, 'Net Debt - GDP Ratio', 'Imported from MetaTrader 5', 'Low', 'BRL', 'MetaTrader 5', 'Unknown', 'Forex', 'BRL'),
(1208, 'RBI Monetary and Credit Information Review', 'Imported from MetaTrader 5', 'Medium', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(1209, 'Infrastructure Output y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(1210, 'GDP m/m', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1211, 'GDP Implicit Price Index q/q', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1212, 'GDP Annualized q/q', 'Imported from MetaTrader 5', 'Medium', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1213, 'Core PCE Price Index m/m', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1214, 'Core PCE Price Index y/y', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1215, 'PCE Price Index m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1216, 'PCE Price Index y/y', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1217, 'Personal Spending m/m', 'Imported from MetaTrader 5', 'Medium', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1218, 'Personal Income m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1219, 'Real PCE m/m', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1220, 'MNI Chicago Business Barometer', 'Imported from MetaTrader 5', 'High', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1221, 'Dallas Fed Trimmed Mean PCE Inflation Rate', 'Imported from MetaTrader 5', 'Low', 'USD', 'MetaTrader 5', 'Unknown', 'Forex', 'USD'),
(1222, 'Budget Balance', 'Imported from MetaTrader 5', 'Low', 'CAD', 'MetaTrader 5', 'Unknown', 'Forex', 'CAD'),
(1223, 'Annual GDP y/y', 'Imported from MetaTrader 5', 'Low', 'INR', 'MetaTrader 5', 'Unknown', 'Forex', 'INR'),
(1224, 'Manufacturing PMI', 'Imported from MetaTrader 5', 'High', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1225, 'Non-Manufacturing PMI', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY'),
(1226, 'Composite PMI', 'Imported from MetaTrader 5', 'Medium', 'CNY', 'MetaTrader 5', 'Unknown', 'Forex', 'CNY');

