# Generated by Django 5.2 on 2025-05-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('country', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=255)),
                ('impact', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('actual', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast', models.CharField(blank=True, max_length=50, null=True)),
                ('previous', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(default='MetaTrader 5', max_length=100)),
                ('supported_minute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.supportedminute')),
            ],
        ),
    ]
