# Generated by Django 5.2 on 2025-05-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_supportedminute'),
        ('economic_events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicevent',
            name='supported_minute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.supportedminute'),
        ),
    ]
